services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: 3306
  users:
    build:
      context: .
      dockerfile: ./users/Dockerfile
    command: sh -c 'wait-for db:3306 -- npm run start'
    ports:
      - "4001:4001"
    expose:
      - "4001"
    depends_on:
      - db
  orders:
    build:
      context: .
      dockerfile: ./orders/Dockerfile
    command: sh -c 'wait-for db:3306 -- npm run start'
    ports:
      - "4000:4000"
    expose:
      - "4000"
    depends_on:
      - db
  catalog:
    build:
      context: .
      dockerfile: ./catalog/Dockerfile
    command: sh -c 'wait-for db:3306 -- npm run start'
    ports:
      - "4002:4002"
    expose:
      - "4002"
    depends_on:
      - db
  images:
    build:
      context: .
      dockerfile: ./images/Dockerfile
    command: sh -c 'wait-for db:3306 -- npm run start'
    ports:
      - "4003:4003"
    expose:
      - "4003"
    depends_on:
      - db

volumes:
    db_data:
