version: "1.0"
services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  users: 
    build: 
      context: .
      dockerfile: ./users/Dockerfile
    command: sh -c 'wait-for db:3306 -- npm run start'
    ports:
      - "4001:4001"
    expose:
      - "4001"
    depends_on:
      - db
  orders: 
    build: 
      context: .
      dockerfile: ./orders/Dockerfile
    command: sh -c 'wait-for db:3306 -- npm run start'
    ports:
      - "4000:4000"
    expose:
      - "4000"
    depends_on:
      - db

volumes:
    db_data: